name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME_FRONTEND: ${{ 'annovo-app' }}
  APP_NAME_BACKEND: ${{ 'annovo-app-backend' }}

jobs:
  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      - name: Docker Build and push
        run: |
          docker build --file=frontend/frontend.dockerfile --rm=true -t registry.heroku.com/$APP_NAME_FRONTEND/web .
          docker push registry.heroku.com/$APP_NAME_FRONTEND/web
      - name: Heroku deploy
        run: heroku container:release web -a $APP_NAME_FRONTEND
  deploy-backend:
    name: Deploy backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ./backend

      - name: Docker login
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Docker Build and push
        run: |
          docker build --file=backend/backend.dockerfile --rm=true -t registry.heroku.com/$APP_NAME_BACKEND/web .
          docker push registry.heroku.com/$APP_NAME_BACKEND/web

      - name: Heroku deploy
        run: heroku container:release web -a $APP_NAME_BACKEND
